import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Entry from '../components/Entry';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bet Statistics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Bet Statistics!
        </h1>

        <p className={styles.description}>
          Enter your prediction for the unemployment rate in the next employment situation report by BLS.<br />
          0.01 ETH is required to participate in this number-guessing game.
        </p>

        <Entry />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright (c) Yoshitaka Shimokawa
        </a>
      </footer>
    </div>
  )
}
